sonar.projectKey=juanpab05_Q-Manager
sonar.organization=juanpab05
sonar.exclusions = report/**, public/**, coverage/**
sonar.cpd.exclusions = src/pages/**/*.test.tsx,src/pages/**/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.testExecutionReportPaths=./test-report.xml