sonar.projectKey=juanpab05_Q-Manager
sonar.organization=juanpab05
sonar.exclusions = report/**, public/**
sonar.cpd.exclusions = src/pages/**/*.test.tsx, src/pages/**/*.test.ts, **/*copy.ts, **/*copy.tsx, **/*copy.test.ts, **/*copy.test.tsx
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
