apiVersion: apps/v1
kind: Deployment
metadata:
  name: qmanager-green
  labels:
    app: qmanager
    color: green
spec:
  replicas: 0   # NO recibe tráfico aún
  selector:
    matchLabels:
      app: qmanager
      color: green
  template:
    metadata:
      labels:
        app: qmanager
        color: green
    spec:
      containers:
        - name: qmanager
          image: juanpazcai/qmanager:v1.0.1   # v1.0.1 stage
          ports:
            - containerPort: 4173