apiVersion: v1
kind: Service
metadata:
  name: qmanager-service
  labels:
    app: qmanager
spec:
  type: ClusterIP
  selector:
    app: qmanager
    color: blue   # 🔵 TODO EL TRÁFICO VA A BLUE AL INICIO
  ports:
    - port: 4173
      targetPort: 4173
      protocol: TCP


